name = "story_bakery/setup_project_configs"
version = "0.1.6"
license = "MIT"
repository = "https://github.com/StoryBakery/setup-project-configs"
includes = ["pesde.toml", "src/**", "README.md"]

[target]
environment = "lune"
bin = "src/init.luau"

[indices]
default = "https://github.com/pesde-pkg/index"

[engines]
pesde = "^0.7.1"
lune = "^0.10.4"
